routes/web.php
	Route::post('posts/new', 'PostsController@new__pts')->name('posts.new__pts');

	## Rutas para los avisos de la web
	Route::get('posts/create/images', 'PostsController@postImages')->name('posts.create.image');
	Route::get('posts-ads/advice', 'PostsController@getAdvice')->name('advice');

	## Rutas para pagos de provincias
	Route::get('payment', 'ShoppingCartController@shoppingReturn')->name('shopping.return');
	Route::post('posts/payments', 'ShoppingCartController@shoppingItems')->name('shopping.items');
	
	## Ruta de pagos
	Route::get('posts/payments', 'PostsController@getPayment')->name('get.payment');

	## Rutas para cargar imagenes, videos y sonidos de los anuncios
	Route::put('posts/{id}/images', 'UploadsController@upload')->name('posts.upload');
	Route::put('posts/{id}/movies', 'UploadsController@uploadMovies')->name('upload.movies');
	Route::put('posts/{id}/sounds', 'UploadsController@uploadSounds')->name('upload.sounds');
	Route::delete('meta/{id}', 'PostsController@drop')->name('meta.destroy');

	## Ruta para subir video.
	Route::get('upload/{slug}/video', 'UploadsController@upload__video')->name('upload.video');
	Route::put('upload/video/{slug}', 'UploadsController@upload_youtube')->name('upload.youtube');

	/*Route::post('{slug}/publish', 'SubscriptionsController@postPayment')->name('post.postPayment');
	Route::get('payment/status', 'SubscriptionsController@getPaymentStatus')->name('payment.status');*/

	## Ruta de posts creados
	Route::get('{slug}/publish/my-posts', 'MyPostsController@publish')->name('my-posts.publish');
	Route::get('my-posts/gallery/{slug}', 'MyPostsController@gallery')->name('my-posts.gallery');
	Route::get('my-posts/renew/{slug}', 'MyPostsController@renew')->name('my-posts.renew');

	## Rutas de seguidores
	Route::post('{username}/follow', 'FollowersController@follow')->name('user.follow');
	Route::post('{username}/unfollow', 'FollowersController@unfollow')->name('user.unfollow');
	Route::get('{username}/followers', 'FollowersController@followers')->name('user.followers');

	## Ruta para añadir favoritos
	Route::post('favorite/add', 'FavoritesController@favorite')->name('post.favorite');

	## Ruta de reporte de anuncios
	Route::get('reports/{slug}/create', 'ReportsController@create')->name('reports.create');
	Route::post('{slug}/reports', 'ReportsController@store')->name('reports.store');

	## Ruta de perfil para usuarios de pago
	Route::get('{username}/page', 'PremiumsController@index')->name('username.index')->middleware('premium');

	## Ruta de demanda de servicios
	Route::get('services/demands', 'DemandsController@index')->name('services.demands')->middleware('premium');

	## Rutas de opiniones para los perfiles de usuarios de pago
	Route::post('messages', 'MessagesController@message')->name('messages.message');
	Route::post('messages/response', 'MessagesController@response')->name('messages.response');
	
	## Ruta de perfil de usuario
	Route::get('profile', 'ProfileController@index')->name('user.profile');
	Route::post('profile/save', 'ProfileController@update')->name('profile.save');

	## Ruta para comprar creditos
	Route::get('credits', 'CreditsController@create')->name('credits.create');
	Route::post('credits/purchase', 'CreditsController@credits__purchase')->name('credits.purchase');

	## Ruta para la red social interna
	Route::get('network', 'NetwController@index')->name('netw');
	Route::post('network/comment', 'NetwController@comment');
	Route::post('network/like', 'NetwController@like');
	Route::get('my/network', 'NetwController@my_network')->name('my/network');
	Route::post('my/network', 'NetwController@mynet_store')->name('my/network_store');

	## Rutas de anuncios, anuncios creados, eventos y favoritos.
	Route::resource('posts', 'PostsController', ['except' => ['index', 'edit', 'show']]);
	Route::resource('my-posts', 'MyPostsController', ['except' => ['create', 'store']]);
	Route::resource('my-events', 'MyEventsController');
	Route::resource('favorites', 'FavoritesController');
});

// Controllers Within The "App\Http\Controllers\Backend" Namespace
Route::namespace('Backend')->prefix('admin')->middleware(['auth', 'master'])->group(function () {

	## Ruta inicial del admin
	Route::get('/', 'MasterController@index')->name('master');

	## Ruta para gestionar anuncios
	Route::get('budgets/post', 'BudgetsPostController@index')->name('budgetsPost.index');
	Route::get('budgets/post/{post}', 'BudgetsPostController@edit')->name('budgetsPost.edit');
	Route::put('budgets/post/{post}/update', 'BudgetsPostController@update')->name('budgetsPost.update');

	## Ruta para gestionar videos, imagenes y audios
	Route::get('budgets/post/{post}/gallery', 'BudgetsPostController@gallery')->name('budgetsPost.gallery');
	Route::get('budgets/post/{post}/movies', 'BudgetsPostController@movies')->name('budgetsPost.movies');
	Route::get('budgets/post/{post}/sounds', 'BudgetsPostController@sounds')->name('budgetsPost.sounds');
	## Rutas para guardar los videos, imagenes y audios
	Route::put('budgets/post/{post}/gallery', 'BudgetsPostController@updateGallery')->name('budgetsPost.updateGallery');
	Route::put('budgets/post/{post}/movies', 'BudgetsPostController@updateMovies')->name('budgetsPost.updateMovies');
	Route::put('budgets/post/{post}/sounds', 'BudgetsPostController@updateSounds')->name('budgetsPost.updateSounds');
	## Rutas para eliminar los videos, imagenes y audios
	Route::get('budgets/delete/{id}/gallery', 'BudgetsPostController@deleteGallery')->name('budgetsPost.deleteGallery');
	Route::get('budgets/delete/{id}/movies', 'BudgetsPostController@deleteMovies')->name('budgetsPost.deleteMovies');
	Route::get('budgets/delete/{id}/sounds', 'BudgetsPostController@deleteSounds')->name('budgetsPost.deleteSounds');

	## Ruta para presupuestos de eventos
	Route::get('budgets', 'BudgetsController@index')->name('budgets.index');
	Route::get('budgets/{id}', 'BudgetsController@show')->name('budgets.show');
	Route::get('budgets/{id}/success', 'BudgetsController@success')->name('budgets.success');
	Route::delete('budgets/{id}', 'BudgetsController@destroy')->name('budgets.destroy');


	## Ruta para notificaciones
	Route::get('manages', 'ManageController@index')->name('manages.index');

	## Ruta para modificar el perfil del Usuario
	Route::get('my-profile', 'ProfileController@index')->name('profile.index');
	Route::post('my-profile', 'ProfileController@update')->name('profile.update');

	## Ruta para generar códigos de suscripciones
	Route::get('encrypted', 'EncryptedController@index')->name('encrypted.index');
	Route::get('encrypted/create', 'EncryptedController@create')->name('encrypted.create');
	Route::post('encrypted', 'EncryptedController@store')->name('encrypted.store');
	Route::delete('encrypted/{id}', 'EncryptedController@delete')->name('encrypted.destroy');
	
	## Rutas para header de paginas
	Route::get('headers/pages', 'HeadersController@headers_pages')->name('headers_pages');
	Route::get('headers/{id}/pages', 'HeadersController@edit_headers_pages')->name('edit.headers_pages');
	Route::put('headers/{id}/update-pages', 'HeadersController@update_headers_pages')->name('update.headers_pages');
	Route::delete('headers/{id}/header-delete_page', 'HeadersController@delete_headers_page')->name('delete.headers_page');

	## Rutas para pagos paypal
	Route::get('paypal/{slug}/edit', 'PaypalController@edit')->name('paypal.edit');
	Route::get('paypal', 'PaypalController@index')->name('paypal.index');
	Route::put('paypal/{slug}/update', 'PaypalController@update')->name('paypal.update');

	## Rutas para headers del frontend
	Route::get('headers/category', 'HeadersController@header__category')->name('headers.index');
	Route::get('headers/subcategory', 'HeadersController@header__category_type')->name('headers.categories-type');
	Route::get('headers/{slug}/edit', 'HeadersController@edit')->name('headers.edit');
	Route::get('headers/{slug}/edit-category_type', 'HeadersController@edit_category__type')->name('headers.edit-category_type');
	Route::put('headers/{slug}/update', 'HeadersController@update')->name('headers.update');
	Route::put('headers/{slug}/update-category_type', 'HeadersController@update_category__type')->name('headers.update-category_type');
	Route::delete('headers/{slug}/category', 'HeadersController@delete_category')->name('headers.delete-category');
	Route::delete('headers/{slug}/category-type', 'HeadersController@delete_category__type')->name('headers.delete-category__type');

	## Ruta de carousel
	Route::get('carousel', 'CarouselController@index')->name('carousel.index');
	Route::post('carousel/{id}', 'CarouselController@store')->name('carousel.store');

	## Rutas de facturaciones de usuarios
	Route::get('subscriptions/users', 'SubscriptionsController@index')->name('subscriptions.index');
	Route::get('subscriptions/{payment}', 'SubscriptionsController@show')->name('subscriptions.show');

	## Rutas de facturaciones de anuncios
	Route::get('advertisements/posts', 'AdvertisementsController@index')->name('advertisements.index');
	Route::get('advertisements/{payment}', 'AdvertisementsController@show')->name('advertisements.show');

	## Rutas para transferir anuncios
	Route::get('{slug}/to', 'PostsController@toTransfer')->name('toTransfer');
	Route::get('search/user/{email}', 'PostsController@search')->name('search.user');
	Route::post('to/transfer', 'PostsController@update')->name('toTransfer.update');

	## Rutas generales de la administración
	Route::resource('mailbox', 'MailboxController');
	Route::resource('categories', 'CategoriesController');
	Route::resource('categories-type', 'CategoriesTypeController');
	Route::resource('published', 'PostsController', ['only' => ['index', 'destroy']]);
	Route::resource('users', 'UsersController', ['except' => ['show']]);
	Route::resource('complaints', 'ComplaintsController', ['only' => ['index', 'destroy']]);
	Route::resource('config', 'ConfigurationsController', ['only' => ['index', 'edit', 'update', 'destroy']]);

app/Http/Controllers/Backend/CategoriesTypeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use App\CategoryType as Type;
use App\Category as Category;
use Carbon\Carbon;
use Session;

class CategoriesTypeController extends Controller
{   
    public function __construct()
    {
        $this->middleware(['auth', 'master']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories_type = Type::with('categorie')->orderBy('category', 'ASC')->get();

        return view('backend.categoriesType.index', [
            'categories_type' => $categories_type
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('id', 'ASC')->get();

        return view('backend.categoriesType.create', [
            'categories' => $categories
        ]);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'category' => 'required',
            'name' => 'required|max:75|unique:categories_type',
            'slug' => 'required|alpha_dash|max:115|unique:categories_type'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        $category = Category::findOrFail($request['category']);
        $request['slug'] = $this->streplace($request['slug']);

        $categories_type = new Type();
        $categories_type->category = $category['id'];
        $categories_type->name = $request['name'];
        $categories_type->slug = $request['slug'];
        $categories_type->save();

        Session::flash('success', 'Nueva Subcategoría agregada');

        return redirect('/admin/categories-type');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories_type = Type::findOrFail($id);

        $categories = Category::orderBy('id', 'ASC')->get();

        return view('backend.categoriesType.edit', [
            'categories_type' => $categories_type,
            'categories' => $categories
        ]);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validatorUpdate(array $data, $id)
    {
        return Validator::make($data, [
            'category' => 'required',
            'name' => 'required|alpha_spaces|max:75', Rule::unique('categories_type', 'name')->ignore($id),
            'slug' => 'required|alpha_dash|max:115', Rule::unique('categories_type', 'slug')->ignore($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validatorUpdate($request->all(), $id)->validate();

        $categories_type = Type::findOrFail($id);
        $categories = Category::findOrFail($request['category']);

        $request['slug'] = $this->streplace($request['slug']);

        $categories_type->name = $request['name'];
        $categories_type->slug = $request['slug'];
        $categories_type->save();

        Session::flash('success', 'La subcategoría ' . $categories_type->name . ' fue editada.');

        return redirect('/admin/categories-type');
    }

    public function destroy($id)
    {
        $category_type = Type::findOrFail($id);
        $category_type->delete();

        Session::flash('success', 'La subcategoría ' . $category_type->name . ' ha sido borrada.');

        return redirect()->back();
    }

    protected function uri()
    {
        return public_path().'/storage/categories/';
    }

    protected function streplace($string) 
    {
        $tofind = 'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûýýþÿŔŕ';
        $replac = 'aaaaaaaceeeeiiiidnoooooouuuuybsaaaaaaaceeeeiiiidnoooooouuuyybyRr';

        $string = utf8_decode($string);
        $string = strtr($string,utf8_decode($tofind),$replac);
        $string = strtolower($string);

        return utf8_encode($string);
    }
}

resources/views/backend/categoriesType/partials/fields-edit.blade.php
<div class="row">
	<div class="col">
		<div class="form-group">
			<label class="control-label">Categoría</label>
			<select class="form-control {{ $errors->has('category') ? ' is-invalid' : '' }} boxed popover-dismiss" name="category" data-toggle="popover" data-placement="top" data-content="Seleccione la categoría para la nueva subcategoría" required>
				@forelse($categories as $key => $category)
				<option value="{{ $category->id }}" {{ (strcmp($category->id, $categories_type->category) == 0) ? 'selected' : '' }}>{{ $category->name }}</option>
				@empty
				<option value="" selected></option>
				@endforelse
			</select>
			@if ($errors->has('category'))
            	<div class="invalid-feedback">{{ $errors->first('category') }}</div>
        	@endif
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="form-group">
			<label class="control-label">Subcategoría</label>
			<input id="name" type="text" name="name" value="{{ $categories_type->name }}" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }} boxed popover-dismiss" data-toggle="popover" data-placement="top" data-content="Sustituye por el nuevo nombre de la subcategoría" required>
			@if ($errors->has('name'))
            	<div class="invalid-feedback">{{ $errors->first('name') }}</div>
        	@endif
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="form-group">
			<label for="slug">Slug</label>
			<input id="slug" type="text" maxlength="75" name="slug" value="{{ $categories_type->slug }}" class="form-control {{ $errors->has('slug') ? ' is-invalid' : '' }}" required>
			@if ($errors->has('slug'))
	        	<div class="invalid-feedback">{{ $errors->first('slug') }}</div>
	    	@else
				<small class="form-text text-muted">
					El “slug” es la versión amigable de la URL del nombre. Suele estar en minúsculas y contiene solo letras, números y guiones.
				</small>
	    	@endif
    	</div>
	</div>
</div>

resources/views/backend/categoriesType/partials/fields.blade.php
<div class="row">
	<div class="col">
		<div class="form-group">
			<label for="category">Categoría</label>
			<select class="form-control {{ $errors->has('category') ? ' is-invalid' : '' }} boxed popover-dismiss" name="category" data-toggle="popover" data-placement="top" data-content="Seleccione la categoría para la nueva Subcategoría" required>
				@forelse($categories as $key => $category)
				<option value="{{ $category->id }}" {{ (old('category') == $category->id) ? 'selected' : '' }}>{{ $category->name }}</option>
				@empty
				<option value="" selected></option>
				@endforelse
			</select>
			@if ($errors->has('category'))
            	<div class="invalid-feedback">{{ $errors->first('category') }}</div>
        	@endif
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="form-group">
			<label for="name">Subcategoría</label>
			<input id="name" type="text" maxlength="50" name="name" value="{{ old('name') }}" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }} boxed popover-dismiss" data-toggle="popover" data-placement="top" data-content="Escribe el nombre de la nueva Subcategoría" required>
			@if ($errors->has('name'))
            	<div class="invalid-feedback">{{ $errors->first('name') }}</div>
        	@endif
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="form-group">
			<label for="slug">Slug</label>
			<input id="slug" type="text" maxlength="75" name="slug" value="{{ old('slug') }}" class="form-control {{ $errors->has('slug') ? ' is-invalid' : '' }}" required>
			@if ($errors->has('slug'))
	        	<div class="invalid-feedback">{{ $errors->first('slug') }}</div>
	    	@else
				<small class="form-text text-muted">
					El “slug” es la versión amigable de la URL del nombre. Suele estar en minúsculas y contiene solo letras, números y guiones.
				</small>
	    	@endif
    	</div>
	</div>
</div>

resources/views/backend/categoriesType/partials/table.blade.php
<table class="table table-striped table-bordered table-hover" id="categoriesType">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">Categoría</th>
			<th scope="col">Nombre</th>
			<th scope="col">Acciones</th>
		</tr>
	</thead>
	<tbody>
		@forelse($categories_type as $key => $type)
		<tr>
			<td>{{ $key + 1 }}</td>
			<td>{{ $type->categorie->name }}</td>
			<td>{{ $type->name }}</td>
			<td class="item-list">
				<div class="item-col fixed item-col-actions-dropdown">
					<div class="item-actions-dropdown">
						<a class="item-actions-toggle-btn">
							<span class="inactive">
								<i class="fa fa-cog"></i>
							</span>
							<span class="active">
								<i class="fa fa-chevron-circle-right"></i>
							</span>
						</a>
						<div class="item-actions-block">
							<ul class="item-actions-list">
								<li>
									{!! Form::model($type, ['route' => ['categories-type.destroy', $type->id], 'method' => 'DELETE']) !!}

									<a href="#" class="remove" onclick="this.parentNode.submit()"><i class="fa fa-trash-o"></i></a>

									{!! Form::close() !!}
								</li>
								<li>
									<a href="{{ route('categories-type.edit', [$type->id]) }}" class="edit"><i class="fa fa-pencil"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</td>
		</tr>
		@empty
		<tr>
			<td colspan="5">No hay Subcategorías creadas</td>
		</tr>
		@endforelse
	</tbody>
</table>